apiVersion: v1
kind: Service
metadata:
  name: splunkmaster
  namespace: default
spec:
  ports:
  - name: splunkweb
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: splunkd
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: forwarder
    port: 9997
    protocol: TCP
    targetPort: 9997
  selector:
    app: splunkmaster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
