apiVersion: v1
kind: Service
metadata:
  name: splunkmaster
  namespace: kong
spec:
  externalName: splunkmaster.default.svc.cluster.local
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  sessionAffinity: None
  type: ExternalName 
status:
  loadBalancer: {}
