apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunkmaster
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: splunkmaster
      role: splunk_standalone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: splunkmaster
        role: splunk_standalone
    spec:
      containers:
      - env:
        - name: SPLUNK_HOME
          value: /opt/splunk
        - name: SPLUNK_ROLE
          value: splunk_standalone
        - name: SPLUNK_PASSWORD
          value: Admin123
        - name: SPLUNK_START_ARGS
          value: --accept-license --answer-yes
        - name: DEBUG
          value: "true"
        image: splunk/splunk:latest
        imagePullPolicy: Always
        name: splunkmaster
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8089
          protocol: TCP
        - containerPort: 8191
          protocol: TCP
        - containerPort: 9997
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/splunk/var
          name: splunk-master-data
        - mountPath: /opt/splunk/etc
          name: splunk-master-config
      dnsPolicy: ClusterFirst
      hostname: splunkmaster
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: splunk-master-config
        persistentVolumeClaim:
          claimName: splunk-master-config
      - name: splunk-master-data
        persistentVolumeClaim:
          claimName: splunk-master-data
status: {}
