---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-master-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 22Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-master-config
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
